{% set version = "2.5" %}

package:
  name: ilamb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/I/ILAMB/ILAMB-{{ version }}.tar.gz
  sha256: d156ab01a2e895fb6ca0da870d385e8872b434e928061f2b440582fa8eb247a5

build:
  number: 2
  skip: True  # [py2k or win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cartopy >=0.17.0
    - cf-units >=2.0.0
    - matplotlib-base >=2.2
    - openssh
    - mpi4py >=1.3.1
    - netcdf4 >=1.5.1.2
    - numpy >=1.11.0
    - scipy >=0.9.0
    - sympy >=0.7.6

test:
  imports:
    - ILAMB
  commands:
    - ilamb-fetch -h
    - ilamb-run -h
    - ilamb-table -h

about:
  home: https://github.com/rubisco-sfa/ILAMB
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The International Land Model Benchmarking Package
  description: |
    The International Land Model Benchmarking (ILAMB) project is a model-data
    intercomparison and integration project designed to improve the performance
    of land models and, in parallel, improve the design of new measurement
    campaigns to reduce uncertainties associated with key land surface processes.
    Building upon past model evaluation studies, the goals of ILAMB are to:

    * develop internationally accepted benchmarks for land model performance,
      promote the use of these benchmarks by the international community for
      model intercomparison,

    * strengthen linkages between experimental, remote sensing, and climate
      modeling communities in the design of new model tests and new measurement
      programs, and

    * support the design and development of a new, open source, benchmarking
      software system for use by the international community.

    It is the last of these goals to which this repository is concerned. We have
    developed a python-based generic benchmarking system, initially focused on
    assessing land model performance.
  doc_url: 'https://www.ilamb.org/doc'
  dev_url: 'https://github.com/rubisco-sfa/ILAMB'

extra:
  recipe-maintainers:
    - jhkennedy
    - nocollier
