travis:
  secure:
    BINSTAR_TOKEN: iyfd3VBxi1pIhxHGKdTYNFLlPHe0L0l0sRDTsy1Cop89Zh+dCb3mRPh2jsYcJ+iaIeKzUsLcsFvhOi9lhpu6Her5Tg7kP2JdwV0wyxcAzdiV1j8cl5uTLmuvd9aj4rHLVj0n7g6xPyWL8rHSgufjhUaggJeClFtl62CW3Ohmty2UlKZJS336x7HOmgl9MnN1lIclLpjqbh6fdVTidem8Uvy+Zsw9A6bSDOy9h3Y4GaSEAyUQD7vPCNjUYb6mKWCZeBVf/EasMzVBHXwQiyAS8wxF8KogLRhozOUvKsxM949Mf4hf1L/1es0I8usQxhFfN3dJaUIXAnZ+omeh144kEJJ84jj1k3HMuOD9wyWt/hqatMGvYZQtfFyCXSpcx5rSe/wcQAtEFW6v7FAabMt2ngRdxHaOfD20O7rGmo+I+0osJTmgwvS3cyxrtx4jsMRlL7Ws2fM2JwTZp5eTHrovIW925kdQxJ0r6e+wGKCWweOI2i/cEp7rAjCj6WYfe6VHjQaKD774EBBNUILzXHn5MmfQkTuGclzugPIDDm4CWp2qGfz7RlOu6PaZ9OClRbjNAk1h6JlpB3gidvsRI1jfZucUiShEbDbdFtehe1SWVUWQVd+moIv6cjvnD436gECyNnqNna+TNYLD/AW9SEjeXtyypD9KHLrAbqIYfItsIIo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
